"""create digest_runs table

Revision ID: 216b61a20187
Revises: 
Create Date: 2026-03-24 21:47:36.638017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '216b61a20187'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digest_runs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('run_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('folder', sa.Text(), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('story_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('status', sa.Text(), server_default='pending', nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('digest_runs')
    # ### end Alembic commands ###
